---
# Homepage Services Configuration
# Adds Queue and Logs navigation items for media management services

- Media Management:
    - Sonarr:
        icon: sonarr.png
        href: http://dataserver2:8989
        description: TV Show Management
        widget:
          type: sonarr
          url: http://dataserver2:8989
          key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
        submenu:
          - name: Queue
            icon: mdi-playlist-play
            href: http://dataserver2:8989/queue
          - name: Logs
            icon: mdi-text-box-outline
            href: http://dataserver2:8989/system/logs/files

    - Radarr:
        icon: radarr.png
        href: http://dataserver2:7878
        description: Movie Management
        widget:
          type: radarr
          url: http://dataserver2:7878
          key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
        submenu:
          - name: Queue
            icon: mdi-playlist-play
            href: http://dataserver2:7878/queue
          - name: Logs
            icon: mdi-text-box-outline
            href: http://dataserver2:7878/system/logs/files

    - Bazarr:
        icon: bazarr.png
        href: http://dataserver2:6767
        description: Subtitle Management
        widget:
          type: bazarr
          url: http://dataserver2:6767
          key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"
        submenu:
          - name: Queue
            icon: mdi-playlist-play
            href: http://dataserver2:6767/history
          - name: Logs
            icon: mdi-text-box-outline
            href: http://dataserver2:6767/system/logs

    - Whisparr:
        icon: whisparr.png
        href: http://dataserver2:6969
        description: Adult Content Management
        widget:
          type: whisparr
          url: http://dataserver2:6969
          key: "{{HOMEPAGE_VAR_WHISPARR_API_KEY}}"
        submenu:
          - name: Queue
            icon: mdi-playlist-play
            href: http://dataserver2:6969/queue
          - name: Logs
            icon: mdi-text-box-outline
            href: http://dataserver2:6969/system/logs/files
